#!/bin/bash
data=../../data/oxide_perangles_GP_train_85x120.tfrecords
net=network_VGG16_w_batch_norm.json
hyp=hyper_params_regressor_custom.json
model=vgg16bnfp16
batch=1024
zoom=1
mode=train
cpuid=0
gpus=1
script=stemdl_regress_horovod.py
while [ $gpus -le 4 ]
do
  logfile=$model-batch-$batch-gpus-$gpus-zoom-$zoom
  checkpt=../../scratch/$model-batch-$batch-gpus-$gpus-zoom-$zoom
  echo mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode --zoom $zoom
  ((gpus ++))
  mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode --zoom $zoom &> $logfile
  rm -r $checkpt
done
echo "all done!"
