#!/bin/bash
data=../../data/oxide_perangles_GP_train_85x120.tfrecords
net=network_ResNet_18.json
hyp=hyper_params_regressor_resnet.json
model=ResNet18
batch=64
gpus=1
mode=train
cpuid=0
script=stemdl_regress_horovod.py
logfile=$model-batch-$batch-gpus-$gpus
checkpt=../../scratch/$model-batch-$batch-gpus-$gpus
echo mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode &> $logfile
mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode &>> $logfile
echo complete!
