#!/bin/sh

if [ $# -eq 0 ]; then
  echo "ERROR: Usage is ./train num_mpi_ranks"
  exit -1
fi

nranks=$1
batch=64
logfile=batch-${batch}-gpus-${nranks}
script=regress.py
cmd="mpirun --allow-run-as-root -np ${nranks} python $script &> $logfile"

echo $cmd
$cmd

rm -rf stemdl_checkpoint/
