#!/bin/bash
data=../../data/oxide_pertiltpattern_1deg_GP_train_85x120.tfrecords
net=network_ResNet_50.json
hyp=hyper_params_classifier_VGG16.json
model=ResNet50_old_reader_dyn_threads
batch=128
gpus=3
mode=train
cpuid=0
script=stemdl_classify_horovod.py
checkpt=../../scratch/$model-batch-$batch-gpus-$gpus
echo mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode
mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode
