#!/bin/bash
data=../../data/oxide_perangles_GP_train_85x120.tfrecords
net=network_ResNet_18_custom.json
hyp=hyper_params_regressor_resnet.json
model=ResNet18
batch=64
gpus=2
mode=train
cpuid=0
script=stemdl_regress_horovod.py
checkpt=$model-batch-$batch-gpus-$gpus
echo mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode
mpirun --allow-run-as-root -np $gpus python $script --data_path $data --checkpt_dir $checkpt --network_config $net --hyper_params $hyp --num_gpus $gpus --batch_size $batch --mode $mode